from .fieldDefinitions import *
from .indexDefinitions import *
from .foreignKeyDefinitions import *
from .rowConversionDefinitions import *

sqlTableDefinitions = {
    "aci_data": (aciDataFields, aciDataIndexes, aciDataForeignKeys),
    "aci_data_change_history": (aciDataChangeHistoryFields, aciDataChangeHistoryIndexes, aciDataChangeHistoryForeignKeys),
    "address": (addressFields, addressIndexes, addressForeignKeys),
    "agent_certification_test": (agentCertificationTestFields, agentCertificationTestIndexes, agentCertificationTestForeignKeys),
    "agent_change_history": (agentChangeHistoryFields, agentChangeHistoryIndexes, agentChangeHistoryForeignKeys),
    "agent": (agentFields, agentIndexes, agentForeignKeys),
    "archive_error_log": (archiveErrorLogFields, archiveErrorLogIndexes, archiveErrorLogForeignKeys),
    "archive_history": (archiveHistoryFields, archiveHistoryIndexes, archiveHistoryForeignKeys),
    "assessorial_change_history": (assessorialChangeHistoryFields, assessorialChangeHistoryIndexes, assessorialChangeHistoryForeignKeys),
    "assessorial": (assessorialFields, assessorialIndexes, assessorialForeignKeys),
    "branch_change_history": (branchChangeHistoryFields, branchChangeHistoryIndexes, branchChangeHistoryForeignKeys),
    "branch": (branchFields, branchIndexes, branchForeignKeys),
    "certification_test": (certificationTestFields, certificationTestIndexes, certificationTestForeignKeys),
    "certification_test_change_history": (certificationTestChangeHistoryFields, certificationTestChangeHistoryIndexes, certificationTestChangeHistoryForeignKeys),
    "certification_test_trainer": (certificationTestTrainerFields, certificationTestTrainerIndexes, certificationTestTrainerForeignKeys),
    "certification_test_trainer_change_history": (certificationTestTrainerChangeHistoryFields, certificationTestTrainerChangeHistoryIndexes, certificationTestTrainerChangeHistoryForeignKeys),
    "city_postal_code": (cityPostalCodeFields, cityPostalCodeIndexes, cityPostalCodeForeignKeys),
    "city_region": (cityRegionFields, cityRegionIndexes, cityRegionForeignKeys),
    "city": (cityFields, cityIndexes, cityForeignKeys),
    "company_change_history": (companyChangeHistoryFields, companyChangeHistoryIndexes, companyChangeHistoryForeignKeys),
    "company": (companyFields, companyIndexes, companyForeignKeys),
    "country": (countryFields, countryIndexes, countryForeignKeys),
    "customer_change_history": (customerChangeHistoryFields, customerChangeHistoryIndexes, customerChangeHistoryForeignKeys),
    "customer_default_assessorial": (customerDefaultAssessorialFields, customerDefaultAssessorialIndexes, customerDefaultAssessorialForeignKeys),
    "customer": (customerFields, customerIndexes, customerForeignKeys),
    "fax": (faxFields, faxIndexes, faxForeignKeys),
    "holiday": (holidayFields, holidayIndexes, holidayForeignKeys),
    "location_change_history": (locationChangeHistoryFields, locationChangeHistoryIndexes, locationChangeHistoryForeignKeys),
    "location_default_assessorial": (locationDefaultAssessorialFields, locationDefaultAssessorialIndexes, locationDefaultAssessorialForeignKeys),
    "location": (locationFields, locationIndexes, locationForeignKeys),
    "order_assessorial": (orderAssessorialFields, orderAssessorialIndexes, orderAssessorialForeignKeys),
    "order_attachment": (orderAttachmentFields, orderAttachmentIndexes, orderAttachmentForeignKeys),
    "order_change_history": (orderChangeHistoryFields, orderChangeHistoryIndexes, orderChangeHistoryForeignKeys),
    "order_dim": (orderDimFields, orderDimIndexes, orderDimForeignKeys),
    "order_driver": (orderDriverFields, orderDriverIndexes, orderDriverForeignKeys),
    "order_status_change_history": (orderStatusChangeHistoryFields, orderStatusChangeHistoryIndexes, orderStatusChangeHistoryForeignKeys),
    "order_status": (orderStatusFields, orderStatusIndexes, orderStatusForeignKeys),
    "order_type": (orderTypeFields, orderTypeIndexes, orderTypeForeignKeys),
    "order": (orderFields, orderIndexes, orderForeignKeys),
    "overnight_maintenance_history": (overnightMaintenanceHistoryFields, overnightMaintenanceHistoryIndexes, overnightMaintenanceHistoryForeignKeys),
    "phone": (phoneFields, phoneIndexes, phoneForeignKeys),
    "position_change_history": (positionChangeHistoryFields, positionChangeHistoryIndexes, positionChangeHistoryForeignKeys),
    "position": (positionFields, positionIndexes, positionForeignKeys),
    "postal_code_region": (postalCodeRegionFields, postalCodeRegionIndexes, postalCodeRegionForeignKeys),
    "postal_code": (postalCodeFields, postalCodeIndexes, postalCodeForeignKeys),
    "rate_area": (rateAreaFields, rateAreaIndexes, rateAreaForeignKeys),
    "rate_change_history": (rateChangeHistoryFields, rateChangeHistoryIndexes, rateChangeHistoryForeignKeys),
    "rate": (rateFields, rateIndexes, rateForeignKeys),
    "region": (regionFields, regionIndexes, regionForeignKeys),
    "special_change_history": (specialChangeHistoryFields, specialChangeHistoryIndexes, specialChangeHistoryForeignKeys),
    "special": (specialFields, specialIndexes, specialForeignKeys),
    "user_change_history": (userChangeHistoryFields, userChangeHistoryIndexes, userChangeHistoryForeignKeys),
    "user": (userFields, userIndexes, userForeignKeys),
}

accessConversionDefinitions = {
    "HTC000_G010_T010 Company Info": convert_HTC000_G010_T010_Company_Info,
    "HTC000_G025_T010 Positions": convert_HTC000_G025_T010_Positions,
    #"HTC000_G090_T010 Staff": convert_HTC000_G090_T010_Staff,
    #   Fix password salt and hash functions
    #
    "HTC010_G000_T000 OrderType Values": convert_HTC010_G000_T000_OrderType_Values,
    #"HTC010_G000_T000 US Zip Codes": convert_HTC010_G000_T000_US_Zip_Codes,
    #   Make more efficient
    #
    "HTC010_G100_T010 Certification Test Catalog": convert_HTC010_G100_T010_Certification_Test_Catalog,
    "HTC300_G000_T000 Archive Update History": convert_HTC300_G000_T000_Archive_Update_History,
    "HTC300_G000_T000 Holidays": convert_HTC300_G000_T000_Holidays,
    "HTC300_G000_T000 Over Night Update History": convert_HTC300_G000_T000_Over_Night_Update_History,
    "HTC300_G000_T020 Branch Info": convert_HTC300_G000_T020_Branch_Info,
    "HTC300_G000_T030 Co Info Chg History": convert_HTC300_G000_T030_Co_Info_Chg_History,
    "HTC300_G000_T040 Branch Info Chg History": convert_HTC300_G000_T040_Branch_Info_Chg_History,
    #"HTC300_G010_T010 DFW_ACI_Data": convert_HTC300_G010_T010_DFW_ACI_Data,
    #"HTC300_G010_T030 ACI Update History": convert_HTC300_G010_T030_ACI_Update_History,
    #"HTC300_G020_T010 Status Values": convert_HTC300_G020_T010_Status_Values,
    #"HTC300_G020_T030 Status Update History": convert_HTC300_G020_T030_Status_Update_History,
    #"HTC300_G025_T025 Positions Change History": convert_HTC300_G025_T025_Positions_Change_History,
    #"HTC300_G030_T010 Customers": convert_HTC300_G030_T010_Customers,
    #"HTC300_G030_T030 Customer Update History": convert_HTC300_G030_T030_Customer_Update_History,
    #"HTC300_G040_T010A Open Orders": convert_HTC300_G040_T010A_Open_Orders,
    #"HTC300_G040_T010B Invoiced Orders": convert_HTC300_G040_T010B_Invoiced_Orders,
    #"HTC300_G040_T010C Remaining Orders": convert_HTC300_G040_T010C_Remaining_Orders,
    #"HTC300_G040_T010D Dock Orders": convert_HTC300_G040_T010D_Dock_Orders,
    #"HTC300_G040_T010E Service Orders": convert_HTC300_G040_T010E_Service_Orders,
    #"HTC400_G040_T010A Orders": convert_HTC400_G040_T010A_Orders,
    #"HTC300_G040_T011A Open Order Assessorials": convert_HTC300_G040_T011A_Open_Order_Assessorials,
    #"HTC300_G040_T011B Invoiced Order Assessorials": convert_HTC300_G040_T011B_Invoiced_Order_Assessorials,
    #"HTC300_G040_T011C Remaining Order Assessorials": convert_HTC300_G040_T011C_Remaining_Order_Assessorials,
    #"HTC300_G040_T011D Dock Order Assessorials": convert_HTC300_G040_T011D_Dock_Order_Assessorials,
    #"HTC300_G040_T011E Service Order Assessorials": convert_HTC300_G040_T011E_Service_Order_Assessorials,
    #"HTC400_G040_T011A Assessorials": convert_HTC400_G040_T011A_Assessorials,
    #"HTC300_G040_T012A Open Order Dims": convert_HTC300_G040_T012A_Open_Order_Dims,
    #"HTC300_G040_T012B Invoiced Order Dims": convert_HTC300_G040_T012B_Invoiced_Order_Dims,
    #"HTC300_G040_T012C Remaining Order Dims": convert_HTC300_G040_T012C_Remaining_Order_Dims,
    #"HTC300_G040_T012D Dock Order Dims": convert_HTC300_G040_T012D_Dock_Order_Dims,
    #"HTC300_G040_T012E Service Order Dims": convert_HTC300_G040_T012E_Service_Order_Dims,
    #"HTC400_G040_T012A Dims": convert_HTC400_G040_T012A_Dims,
    #"HTC300_G040_T013A Open Order Drivers": convert_HTC300_G040_T013A_Open_Order_Drivers,
    #"HTC300_G040_T013B Invoiced Order Drivers": convert_HTC300_G040_T013B_Invoiced_Order_Drivers,
    #"HTC300_G040_T013C Remaining Order Drivers": convert_HTC300_G040_T013C_Remaining_Order_Drivers,
    #"HTC300_G040_T013D Dock Order Drivers": convert_HTC300_G040_T013D_Dock_Order_Drivers,
    #"HTC300_G040_T013E Service Order Drivers": convert_HTC300_G040_T013E_Service_Order_Drivers,
    #"HTC400_G040_T013A Drivers": convert_HTC400_G040_T013A_Drivers,
    #"HTC300_G040_T014A Open Order Attachments": convert_HTC300_G040_T014A_Open_Order_Attachments,
    #"HTC300_G040_T014B Invoiced Order Attachments": convert_HTC300_G040_T014B_Invoiced_Order_Attachments,
    #"HTC300_G040_T014C Remaining Order Attachments": convert_HTC300_G040_T014C_Remaining_Order_Attachments,
    #"HTC300_G040_T014D Dock Order Attachments": convert_HTC300_G040_T014D_Dock_Order_Attachments,
    #"HTC300_G040_T014E Service Order Attachments": convert_HTC300_G040_T014E_Service_Order_Attachments,
    #"HTC400_G040_T014A Attachments": convert_HTC400_G040_T014A_Attachments,
    #"HTC300_G040_T030 Orders Update History": convert_HTC300_G040_T030_Orders_Update_History,
    #"HTC300_G050_T010 Accessorials": convert_HTC300_G050_T010_Accessorials,
    #"HTC300_G050_T030 Accessorials Update History": convert_HTC300_G050_T030_Accessorials_Update_History,
    #"HTC300_G060_T010 Addresses": convert_HTC300_G060_T010_Addresses,
    #"HTC300_G060_T030 Addresses Update History": convert_HTC300_G060_T030_Addresses_Update_History,
    #"HTC300_G070_T010 Rates": convert_HTC300_G070_T010_Rates,
    #"HTC300_G070_T030 Rates Update History": convert_HTC300_G070_T030_Rates_Update_History,
    #"HTC300_G080_T010 Agents": convert_HTC300_G080_T010_Agents,
    #"HTC300_G090_T030 Staff Chg History": convert_HTC300_G090_T030_Staff_Chg_History,
    #"HTC400_G900_T010 Archive Event Log": convert_HTC400_G900_T010_Archive_Event_Log,
}
