from ...imports import *

archiveHistoryFields: List[Field] = [
    Field(fieldName="id", fieldDetails="INTEGER PRIMARY KEY NOT NULL IDENTITY(1, 1)"),
    Field(fieldName="date_archived", fieldDetails="DATETIME2"),
    Field(fieldName="open_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="open_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="open_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="open_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="open_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="invoiced_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="invoiced_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="invoiced_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="invoiced_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="invoiced_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="remaining_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="remaining_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="remaining_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="remaining_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="remaining_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="dock_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="dock_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="dock_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="dock_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="dock_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="service_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="service_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="service_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="service_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="service_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="active_order_history", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="active_order_hawbs", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_history", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="archived_order_hawbs", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_orders", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_assessorials", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_dimensions", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_drivers", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_attachments", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_history", fieldDetails="INTEGER DEFAULT (0)"),
    Field(fieldName="removed_order_hawbs", fieldDetails="INTEGER DEFAULT (0)"),
]

archiveHistoryIndexes: List[Index] = [
]

archiveHistoryForeignKeys: List[ForeignKey] = [
]

def createArchiveHistoryTable(conn):
    archiveHistoryTable = SqlTable('archive_history', conn, archiveHistoryFields, archiveHistoryIndexes, archiveHistoryForeignKeys)
    archiveHistoryTable.createTable()
    archiveHistoryTable.addIndexes()

    return archiveHistoryTable

def addArchiveHistory(
    conn : Connection,
    dateArchived : str,
    openOrders : int,
    openOrderAssessorials : int,
    openOrderDimensions : int,
    openOrderDrivers : int,
    openOrderAttachments : int,
    invoicedOrders : int,
    invoicedOrderAssessorials : int,
    invoicedOrderDimensions : int,
    invoicedOrderDrivers : int,
    invoicedOrderAttachments : int,
    remainingOrders : int,
    remainingOrderAssessorials : int,
    remainingOrderDimensions : int,
    remainingOrderDrivers : int,
    remainingOrderAttachments : int,
    dockOrders : int,
    dockOrderAssessorials : int,
    dockOrderDimensions : int,
    dockOrderDrivers : int,
    dockOrderAttachments : int,
    serviceOrders : int,
    serviceOrderAssessorials : int,
    serviceOrderDimensions : int,
    serviceOrderDrivers : int,
    serviceOrderAttachments : int,
    activeOrderHistory : int,
    activeOrderHawbs : int,
    archivedOrders : int,
    archivedOrderAssessorials : int,
    archivedOrderDimensions : int,
    archivedOrderDrivers : int,
    archivedOrderAttachments : int,
    archivedOrderHistory : int,
    archivedOrderHawbs : int,
    removedOrders : int,
    removedOrderAssessorials : int,
    removedOrderDimensions : int,
    removedOrderDrivers : int,
    removedOrderAttachments : int,
    removedOrderHistory : int,
    removedOrderHawbs : int,
) -> int:
    archiveHistoryRow = conn.sqlGetInfo(
      'archive_history',
      'id', 
      whereDetails={
          'date_archived': dateArchived,
          'open_orders': openOrders,
          'open_order_assessorials': openOrderAssessorials,
          'open_order_dimensions': openOrderDimensions,
          'open_order_drivers': openOrderDrivers,
          'open_order_attachments': openOrderAttachments,
          'invoiced_orders': invoicedOrders,
          'invoiced_order_assessorials': invoicedOrderAssessorials,
          'invoiced_order_dimensions': invoicedOrderDimensions,
          'invoiced_order_drivers': invoicedOrderDrivers,
          'invoiced_order_attachments': invoicedOrderAttachments,
          'remaining_orders': remainingOrders,
          'remaining_order_assessorials': remainingOrderAssessorials,
          'remaining_order_dimensions': remainingOrderDimensions,
          'remaining_order_drivers': remainingOrderDrivers,
          'remaining_order_attachments': remainingOrderAttachments,
          'dock_orders': dockOrders,
          'dock_order_assessorials': dockOrderAssessorials,
          'dock_order_dimensions': dockOrderDimensions,
          'dock_order_drivers': dockOrderDrivers,
          'dock_order_attachments': dockOrderAttachments,
          'service_orders': serviceOrders,
          'service_order_assessorials': serviceOrderAssessorials,
          'service_order_dimensions': serviceOrderDimensions,
          'service_order_drivers': serviceOrderDrivers,
          'service_order_attachments': serviceOrderAttachments,
          'active_order_history': activeOrderHistory,
          'active_order_hawbs': activeOrderHawbs,
          'archived_orders': archivedOrders,
          'archived_order_assessorials': archivedOrderAssessorials,
          'archived_order_dimensions': archivedOrderDimensions,
          'archived_order_drivers': archivedOrderDrivers,
          'archived_order_attachments': archivedOrderAttachments,
          'archived_order_history': archivedOrderHistory,
          'archived_order_hawbs': archivedOrderHawbs,
          'removed_orders': removedOrders,
          'removed_order_assessorials': removedOrderAssessorials,
          'removed_order_dimensions': removedOrderDimensions,
          'removed_order_drivers': removedOrderDrivers,
          'removed_order_attachments': removedOrderAttachments,
          'removed_order_history': removedOrderHistory,
          'removed_order_hawbs': removedOrderHawbs
      }
    )
    if archiveHistoryRow:
        return archiveHistoryRow[0].id
    data = {
        'date_archived' : dateArchived,
        'open_orders' : openOrders,
        'open_order_assessorials' : openOrderAssessorials,
        'open_order_dimensions' : openOrderDimensions,
        'open_order_drivers' : openOrderDrivers,
        'open_order_attachments' : openOrderAttachments,
        'invoiced_orders' : invoicedOrders,
        'invoiced_order_assessorials' : invoicedOrderAssessorials,
        'invoiced_order_dimensions' : invoicedOrderDimensions,
        'invoiced_order_drivers' : invoicedOrderDrivers,
        'invoiced_order_attachments' : invoicedOrderAttachments,
        'remaining_orders' : remainingOrders,
        'remaining_order_assessorials' : remainingOrderAssessorials,
        'remaining_order_dimensions' : remainingOrderDimensions,
        'remaining_order_drivers' : remainingOrderDrivers,
        'remaining_order_attachments' : remainingOrderAttachments,
        'dock_orders' : dockOrders,
        'dock_order_assessorials' : dockOrderAssessorials,
        'dock_order_dimensions' : dockOrderDimensions,
        'dock_order_drivers' : dockOrderDrivers,
        'dock_order_attachments' : dockOrderAttachments,
        'service_orders' : serviceOrders,
        'service_order_assessorials' : serviceOrderAssessorials,
        'service_order_dimensions' : serviceOrderDimensions,
        'service_order_drivers' : serviceOrderDrivers,
        'service_order_attachments' : serviceOrderAttachments,
        'active_order_history' : activeOrderHistory,
        'active_order_hawbs' : activeOrderHawbs,
        'archived_orders' : archivedOrders,
        'archived_order_assessorials' : archivedOrderAssessorials,
        'archived_order_dimensions' : archivedOrderDimensions,
        'archived_order_drivers' : archivedOrderDrivers,
        'archived_order_attachments' : archivedOrderAttachments,
        'archived_order_history' : archivedOrderHistory,
        'archived_order_hawbs' : archivedOrderHawbs,
        'removed_orders' : removedOrders,
        'removed_order_assessorials' : removedOrderAssessorials,
        'removed_order_dimensions' : removedOrderDimensions,
        'removed_order_drivers' : removedOrderDrivers,
        'removed_order_attachments' : removedOrderAttachments,
        'removed_order_history' : removedOrderHistory,
        'removed_order_hawbs' : removedOrderHawbs,
    }
    conn.sqlInsertRow('archive_history', data)
    conn.commit()

    return conn.sqlGetLastIdCreated('archive_history')